# Version is now obsolete
#version: "3.8"

services:
  devpkg-watchtower:
    image: containrrr/watchtower
    container_name: devpkg-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: dev-cache
      WATCHTOWER_POLL_INTERVAL: 3600

  devpkg-dozzle:
    image: amir20/dozzle:latest
    container_name: devpkg-dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080/tcp"
    environment:
      DOZZLE_HOSTNAME: dev-cache
      # Uncomment to enable container actions (stop, start, restart). See https://dozzle.dev/guide/actions
      # - DOZZLE_ENABLE_ACTIONS=true
      #
      # Uncomment to allow access to container shells. See https://dozzle.dev/guide/shell
      # - DOZZLE_ENABLE_SHELL=true
      #
      # Uncomment to enable authentication. See https://dozzle.dev/guide/authentication
      # - DOZZLE_AUTH_PROVIDER=simple
    restart: always
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s

  devpkg-restarter:
    image: docker-registry.markridgwell.com/credfeto/cache-restarter:latest
    container_name: devpkg-restarter
    hostname: devpkg-restarter
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    network_mode: none
    environment:
      - RESTARTER_TAG=devpkg
    cap_drop:
      - ALL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#    networks:
#      backend:

  devpkg-proxy:
    image: docker-registry.markridgwell.com/credfeto/cache-proxy:latest
    container_name: devpkg-proxy
    hostname: dev-proxy
    restart: always
    stop_grace_period: 500s
    stop_signal: SIGINT
#    environment:
#      - Proxy__UpstreamUrls__0=https://api.nuget.org
#      - Proxy__PublicUrl=https://api.nuget.local:5555
#      - Proxy__Packages=/data
#      - Proxy__JsonMaxAgeSeconds=30
    ports:
      - "8085:8080/tcp"
    volumes:
      - cache_proxy:/data
      - ./certs/builds.dotnet.local.pfx:/usr/src/app/server.pfx:r
      - ./cache.appsettings.json:/usr/src/app/appsettings-local.json:ro
    labels:
      - "autoheal=devpkg"
    networks:
      backend:

  devpkg-nuget:
    image: docker-registry.markridgwell.com/credfeto/nuget-proxy:latest
    container_name: devpkg-nuget
    hostname: nuget
    restart: always
    stop_grace_period: 500s
    stop_signal: SIGINT
    environment:
      - Proxy__UpstreamUrls__0=https://api.nuget.org
      - Proxy__PublicUrl=${API_NUGET_URL}
      - Proxy__Metadata=/data/json
      - Proxy__Packages=/data/packages
      - Proxy__JsonMaxAgeSeconds=30
    ports:
      - "8081:8081/tcp"
      - "8081:8081/udp"
    volumes:
      - cache_api_nuget_org:/data
      - ./certs/api.nuget.local.pfx:/usr/src/app/server.pfx:r
    labels:
      - "autoheal=devpkg"
    networks:
      backend:

  devpkg-funfair-release:
    image: docker-registry.markridgwell.com/credfeto/nuget-proxy:latest
    container_name: devpkg-funfair-release
    hostname: funfair-release
    restart: always
    stop_grace_period: 500s
    stop_signal: SIGINT
    environment:
      - Proxy__UpstreamUrls__0=https://dotnet-nuget.s3.eu-west-1.amazonaws.com
      - Proxy__UpstreamUrls__1=https://s3.eu-west-1.amazonaws.com/dotnet-nuget
      - Proxy__UpstreamUrls__2=https://s3-eu-west-1.amazonaws.com/dotnet-nuget
      - Proxy__PublicUrl=${FUNFAIR_NUGET_URL}
      - Proxy__Metadata=/data/json
      - Proxy__Packages=/data/packages
      - Proxy__JsonMaxAgeSeconds=600
    ports:
      - "8082:8081/tcp"
      - "8082:8081/tcp"
    volumes:
      - cache_funfair_release:/data
      - ./certs/funfair.nuget.local.pfx:/usr/src/app/server.pfx:r
    labels:
      - "autoheal=devpkg"
    networks:
      backend:

  devpkg-funfair-prerelease:
    image: docker-registry.markridgwell.com/credfeto/nuget-proxy:latest
    container_name: devpkg-funfair-prerelease
    hostname: funfair-prerelease
    restart: always
    stop_grace_period: 500s
    stop_signal: SIGINT
    environment:
      - Proxy__UpstreamUrls__0=https://dotnet-nuget-prerelease.s3.eu-west-1.amazonaws.com
      - Proxy__UpstreamUrls__1=https://s3.eu-west-1.amazonaws.com/dotnet-nuget-prerelease
      - Proxy__UpstreamUrls__2=https://s3-eu-west-1.amazonaws.com/dotnet-nuget-prerelease
      - Proxy__PublicUrl=${FUNFAIR_PRERELEASE_NUGET_URL}
      - Proxy__Metadata=/data/json
      - Proxy__Packages=/data/packages
      - Proxy__JsonMaxAgeSeconds=600
    ports:
      - "8083:8081/tcp"
      - "8083:8081/tcp"
    volumes:
      - cache_funfair_prerelease:/data
      - ./certs/funfair.nuget.local.pfx:/usr/src/app/server.pfx:r
    labels:
      - "autoheal=devpkg"
    networks:
      backend:

  devpkg-npm:
    image: verdaccio/verdaccio:latest
    container_name: devpkg-npm
    hostname: npm
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    environment:
      - VERDACCIO_PORT=4873
      - VERDACCIO_PUBLIC_URL=${NPM_URL}
    ports:
      - "8084:4873/tcp"
    volumes:
      - ./npm/conf:/verdaccio/conf
      - cache_npm_storage:/verdaccio/storage
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:4873/-/ping -O /dev/null || exit 1
      interval: 5s
      timeout: 4s
      retries: 5
      start_period: 120s
    labels:
      - "autoheal=devpkg"
    networks:
      backend:

  devpkg-nginx:
    image: docker-registry.markridgwell.com/credfeto/cache-nginx:latest
    container_name: devpkg-nginx
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    volumes:
      - ./certs:/etc/nginx/ssl:r
      - cache_nginx:/var/cache/nginx/proxy
    ports:
      - 5555:5555/tcp
      - 5555:5555/udp
      - 5554:5554/tcp
    depends_on:
      devpkg-proxy:
        condition: service_healthy
      devpkg-nuget:
        condition: service_healthy
      devpkg-funfair-prerelease:
        condition: service_healthy
      devpkg-funfair-release:
        condition: service_healthy
      devpkg-npm:
        condition: service_healthy
    networks:
      backend:
      frontend:
        aliases:
          - api.nuget.local
          - funfair.nuget.local
          - funfair-prerelease.nuget.local
          - npm.local
          - builds.dotnet.local

#  devpkg-cache:
#    image: docker-registry.markridgwell.com/credfeto/cache-checker:latest
#    container_name: devpkg-cache
#    restart: always
#    stop_grace_period: 5s
#    stop_signal: SIGINT
#    depends_on:
#      devpkg-nginx:
#        condition: service_healthy
#    volumes:
#      - ./certs:/local/certs:r
#      - cache_downloads:/local/downloads
#      - cache_dotnet:/local/dotnet
#    labels:
#      - "autoheal=devpkg"
#    networks:
#      frontend:

networks:
  backend:
    driver: bridge

  frontend:
    driver: bridge

volumes:
  cache_downloads:
    name: cache_downloads
    external: true
  cache_dotnet:
    name: cache_dotnet
    external: true
  cache_proxy:
    name: cache_proxy
    external: true
  cache_api_nuget_org:
    name: cache_api_nuget_org
    external: true
  cache_funfair_release:
    name: cache_funfair_release
    external: true
  cache_funfair_prerelease:
    name: cache_funfair_prerelease
    external: true
  cache_npm_conf:
    name: cache_npm_conf
    external: true
  cache_npm_storage:
    name: cache_npm_storage
    external: true
  cache_nginx:
    name: cache_nginx
    external: true

