# Version is now obsolete
#version: "3.8"

services:

  devpkg-nuget:
    image: docker-registry.markridgwell.com/credfeto/nuget-proxy:latest
    container_name: devpkg-nuget
    hostname: nuget
    restart: always
    stop_grace_period: 500s
    stop_signal: SIGINT
    environment:
      - Proxy__UpstreamUrl__0=https://api.nuget.org
      - Proxy__PublicUrl=https://api.nuget.local:5555
      - Proxy__Packages=/data
    volumes:
      - /cache/nuget/api.nuget.local:/data
    networks:
      backend:

  devpkg-funfair-release:
    image: docker-registry.markridgwell.com/credfeto/nuget-proxy:latest
    container_name: devpkg-funfair-release
    hostname: funfair-release
    restart: always
    stop_grace_period: 500s
    stop_signal: SIGINT
    environment:
      - Proxy__UpstreamUrl__0=https://dotnet-nuget.s3.eu-west-1.amazonaws.com
      - Proxy__UpstreamUrl__1=https://s3.eu-west-1.amazonaws.com/dotnet-nuget
      - Proxy__PublicUrl=https://funfair.nuget.local:5555
      - Proxy__Packages=/data
    volumes:
      - /cache/nuget/funfair.nuget.local:/data
    networks:
      backend:

  devpkg-funfair-prerelease:
    image: docker-registry.markridgwell.com/credfeto/nuget-proxy:latest
    container_name: devpkg-funfair-prerelease
    hostname: funfair-prerelease
    restart: always
    stop_grace_period: 500s
    stop_signal: SIGINT
    environment:
      - Proxy__UpstreamUrl__0=https://dotnet-nuget-prerelease.s3.eu-west-1.amazonaws.com
      - Proxy__UpstreamUrl__1=https://s3.eu-west-1.amazonaws.com/dotnet-nuget-prerelease
      - Proxy__PublicUrl=https://funfair.nuget.local:5555
      - Proxy__Packages=/data
    volumes:
      - /cache/nuget/funfair.nuget.local:/data
    networks:
      backend:

  devpkg-npm:
    image: verdaccio/verdaccio:latest
    container_name: devpkg-npm
    hostname: npm
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    environment:
      - VERDACCIO_PORT=8080
      - VERDACCIO_PUBLIC_URL=https://npm.local:5555
    volumes:
      - ./npm/conf:/verdaccio/conf
      - ./npm/plugins:/verdaccio/plugins
      - /cache/npm/storage:/verdaccio/storage
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:8080 || exit 1
      interval: 5s
      timeout: 4s
      retries: 5
      start_period: 120s
    networks:
      backend:

  devpkg-nginx:
    image: nginx:stable-alpine
    container_name: devpkg-nginx
    restart: unless-stopped
    stop_grace_period: 5s
    stop_signal: SIGINT
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/ssl
      - /cache/nginx:/var/cache/nginx/proxy
    ports:
      - 5555:5555/tcp
      - 5554:5554/tcp
    healthcheck:
      test: curl --fail http://localhost/health || exit 1
      interval: 5s
      timeout: 4s
      retries: 6
      start_period: 120s
    depends_on:
      devpkg-nuget:
        condition: service_healthy
      devpkg-funfair-prerelease:
        condition: service_healthy
      devpkg-funfair-release:
        condition: service_healthy
      devpkg-npm:
        condition: service_healthy
    networks:
      backend:
      frontend:
        aliases:
          - api.nuget.local
          - funfair.nuget.local
          - funfair-prerelease.nuget.local
          - npm.local

  cache:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: devpkg-cache
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    depends_on:
      devpkg-nginx:
        condition: service_healthy
    volumes:
      - ./certs/api.nuget.local.pem:/usr/local/share/ca-certificates/api.nuget.local.crt:r
      - ./certs/funfair.nuget.local.pem:/usr/local/share/ca-certificates/funfair.nuget.local.crt:r
      - ./certs/funfair-prerelease.nuget.local.pem:/usr/local/share/ca-certificates/funfair-prerelease.nuget.local.crt:r
      - ./certs/npm.local.crt:/usr/local/share/ca-certificates/npm.local.crt:r
      - ./cache/populate:/root/populate:r
      - ./cache/healthcheck:/root/healthcheck:r
      - ./cache/nuget.config:/root/.nuget/NuGet/NuGet.Config:r
    command:
      /root/populate
    healthcheck:
      test: /root/healthcheck
      interval: 5s
      timeout: 4s
      retries: 5
      start_period: 120s
    networks:
      frontend:

networks:
  backend:
    driver: bridge

  frontend:
    driver: bridge
