# Version is now obsolete
#version: "3.8"

services:

  devpkg-nuget-postgresql:
    container_name: devpkg-nuget-postgresql
    hostname: nuget-postgresql
    image: postgres:16
    restart: unless-stopped
    stop_grace_period: 500s
    stop_signal: SIGINT
    environment:
      POSTGRES_USER: nuget
      POSTGRES_PASSWORD: nuget
      PGUSER: nuget
    volumes:
      - /cache/nuget/db/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      backend:

  devpkg-nuget:
    image: bagetter/bagetter:latest
    container_name: devpkg-nuget
    hostname: nuget
    restart: unless-stopped
    stop_grace_period: 500s
    stop_signal: SIGINT
    environment:
      - AllowPackageOverwrites=true
      - ApiKey=Upload
      - Database__ConnectionString=Server=nuget-postgresql;Port=5432;Database=nuget;User Id=nuget;Password=nuget;
      - Database__Type=PostgreSql
      - Logging__Console__LogLevel__Default=Warning
      - MaxPackageSizeGiB=10
      - MaxVersionsPerPackage=5
      - Mirror__Enabled=true
      - Mirror__PackageDownloadTimeoutSeconds=60000
      - Mirror__PackageSource=https://api.nuget.org/v3/index.json
      - PackageDeletionBehavior=HardDelete
      - Search__Type=Database
      - Storage__Path=/data/packages
      - Storage__Type=FileSystem
    volumes:
      - /cache/nuget/security/nuget:/root/.aspnet
      - /cache/nuget/packages/nuget:/data
      - /cache/nuget/db/nuget:/data/db
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1
      interval: 5s
      timeout: 4s
      retries: 5
    depends_on:
      devpkg-nuget-postgresql:
        condition: service_healthy
    networks:
      backend:

  devpkg-funfair-release:
    image: bagetter/bagetter:latest
    container_name: devpkg-funfair-release
    hostname: funfair-release
    restart: unless-stopped
    stop_grace_period: 500s
    stop_signal: SIGINT
    environment:
      - AllowPackageOverwrites=true
      - ApiKey=Upload
      - Database__ConnectionString=Server=nuget-postgresql;Port=5432;Database=funfair-release;User Id=nuget;Password=nuget;
      - Database__Type=PostgreSql
      - Logging__Console__LogLevel_Default=Warning
      - MaxPackageSizeGiB=10
      - MaxVersionsPerPackage=5
      - Mirror__Enabled=true
      - Mirror__PackageDownloadTimeoutSeconds=60000
      - Mirror__PackageSource=https://dotnet-nuget.s3.eu-west-1.amazonaws.com/index.json
      - PackageDeletionBehavior=HardDelete
      - Search__Type=Database
      - Storage__Path=/data/packages
      - Storage__Type=FileSystem
    volumes:
      - /cache/nuget/security/nuget:/root/.aspnet
      - /cache/nuget/packages/funfair-release:/data
      - /cache/nuget/db/funfair-release:/data/db
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1
      interval: 5s
      timeout: 4s
      retries: 5
    depends_on:
      devpkg-nuget-postgresql:
        condition: service_healthy
    networks:
      backend:

  devpkg-funfair-prerelease:
    image: bagetter/bagetter:latest
    container_name: devpkg-funfair-prerelease
    hostname: funfair-prerelease
    restart: unless-stopped
    stop_grace_period: 500s
    stop_signal: SIGINT
    environment:
      - AllowPackageOverwrites=true
      - ApiKey=Upload
      - Database__ConnectionString=Server=nuget-postgresql;Port=5432;Database=funfair-prerelease;User Id=nuget;Password=nuget;
      - Database__Type=PostgreSql
      - Logging__Console__LogLevel_Default=Warning
      - MaxPackageSizeGiB=10
      - MaxVersionsPerPackage=5
      - Mirror__Enabled=true
      - Mirror__PackageDownloadTimeoutSeconds=60000
      - Mirror__PackageSource=https://dotnet-nuget-prerelease.s3.eu-west-1.amazonaws.com/index.json
      - PackageDeletionBehavior=HardDelete
      - Search__Type=Database
      - Storage__Path=/data/packages
      - Storage__Type=FileSystem
    volumes:
      - /cache/nuget/security/nuget:/root/.aspnet
      - /cache/nuget/packages/funfair-prerelease:/data
      - /cache/nuget/db/funfair-prerelease:/data/db
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1
      interval: 5s
      timeout: 4s
      retries: 5
    depends_on:
      devpkg-nuget-postgresql:
        condition: service_healthy
    networks:
      backend:

  devpkg-npm:
    image: verdaccio/verdaccio:latest
    container_name: devpkg-npm
    hostname: npm
    restart: unless-stopped
    stop_grace_period: 5s
    stop_signal: SIGINT
    environment:
      - VERDACCIO_PORT=8080
      - VERDACCIO_PUBLIC_URL=http://npm.local:5554
    volumes:
      - ./npm/conf:/verdaccio/conf
      - ./npm/plugins:/verdaccio/plugins
      - /cache/npm/storage:/verdaccio/storage
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:8080 || exit 1
      interval: 5s
      timeout: 4s
      retries: 5
    networks:
      backend:

  devpkg-nginx:
    image: nginx:stable-alpine
    container_name: devpkg-nginx
    restart: unless-stopped
    stop_grace_period: 5s
    stop_signal: SIGINT
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/ssl
      - /cache/nginx:/var/cache/nginx/proxy
    ports:
      - 5555:443
      - 5554:80
    healthcheck:
      test: curl --fail http://localhost/health || exit 1
      interval: 5s
      timeout: 4s
      retries: 5
    depends_on:
      devpkg-nuget:
        condition: service_healthy
      devpkg-funfair-prerelease:
        condition: service_healthy
      devpkg-funfair-release:
        condition: service_healthy
      devpkg-npm:
        condition: service_healthy
    networks:
      backend:
      frontend:
        aliases:
          - api.nuget.local
          - funfair.nuget.local
          - funfair-prerelease.nuget.local
          - npm.local

  cache:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: devpkg-cache
    restart: unless-stopped
    stop_grace_period: 5s
    stop_signal: SIGINT
    depends_on:
      devpkg-nginx:
        condition: service_healthy
    volumes:
      - ./certs/api.nuget.local.pem:/usr/local/share/ca-certificates/api.nuget.local.crt:r
      - ./certs/funfair.nuget.local.pem:/usr/local/share/ca-certificates/funfair.nuget.local.crt:r
      - ./certs/funfair-prerelease.nuget.local.pem:/usr/local/share/ca-certificates/funfair-prerelease.nuget.local.crt:r
      - ./certs/npm.local.crt:/usr/local/share/ca-certificates/npm.local.crt:r
      - ./cache/populate:/root/populate
      - ./cache/healthcheck:/root/healthcheck
      - ./cache/nuget.config:/root/.nuget/NuGet/NuGet.Config
    command:
      /root/populate
    healthcheck:
      test: /root/healthcheck
      interval: 5s
      timeout: 4s
      retries: 5
    networks:
      frontend:

networks:
  backend:
    driver: bridge

  frontend:
    driver: bridge