# Version is now obsolete
#version: "3.8"

services:

  devpkg-restarter:
    image: docker-registry.markridgwell.com/credfeto/cache-restarter:latest
    container_name: devpkg-restarter
    hostname: restarter
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    network_mode: none
    cap_drop:
      - ALL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#    networks:
#      backend:

  devpkg-proxy:
    image: docker-registry.markridgwell.com/credfeto/cache-proxy:latest
    container_name: devpkg-proxy
    hostname: proxy
    restart: always
    stop_grace_period: 500s
    stop_signal: SIGINT
    environment:
      - Proxy__UpstreamUrl__0=https://api.nuget.org
      - Proxy__PublicUrl=https://api.nuget.local:5555
      - Proxy__Packages=/data
      - Proxy__JsonMaxAgeSeconds=30
    ports:
      - 8000:8080
    volumes:
      - cache_proxy:/data
      - ./certs/builds.dotnet.local.pfx:/usr/src/app/server.pfx:r
    labels:
      - "autoheal=devpkg"
    networks:
      backend:

  devpkg-nuget:
    image: docker-registry.markridgwell.com/credfeto/nuget-proxy:latest
    container_name: devpkg-nuget
    hostname: nuget
    restart: always
    stop_grace_period: 500s
    stop_signal: SIGINT
    environment:
      - Proxy__UpstreamUrl__0=https://api.nuget.org
      - Proxy__PublicUrl=https://api.nuget.local:5555
      - Proxy__Packages=/data
      - Proxy__JsonMaxAgeSeconds=30
    volumes:
      - cache_api_nuget_org:/data
      - ./certs/api.nuget.local.pfx:/usr/src/app/server.pfx:r
    labels:
      - "autoheal=devpkg"
    networks:
      backend:

  devpkg-funfair-release:
    image: docker-registry.markridgwell.com/credfeto/nuget-proxy:latest
    container_name: devpkg-funfair-release
    hostname: funfair-release
    restart: always
    stop_grace_period: 500s
    stop_signal: SIGINT
    environment:
      - Proxy__UpstreamUrl__0=https://dotnet-nuget.s3.eu-west-1.amazonaws.com
      - Proxy__UpstreamUrl__1=https://s3.eu-west-1.amazonaws.com/dotnet-nuget
      - Proxy__UpstreamUrl__2=https://s3-eu-west-1.amazonaws.com/dotnet-nuget
      - Proxy__PublicUrl=https://funfair.nuget.local:5555
      - Proxy__Packages=/data
      - Proxy__JsonMaxAgeSeconds=600
    ports:
      - 8001:8080
    volumes:
      - cache_funfair_prerelease:/data
      - ./certs/funfair.nuget.local.pfx:/usr/src/app/server.pfx:r
    labels:
      - "autoheal=devpkg"
    networks:
      backend:

  devpkg-funfair-prerelease:
    image: docker-registry.markridgwell.com/credfeto/nuget-proxy:latest
    container_name: devpkg-funfair-prerelease
    hostname: funfair-prerelease
    restart: always
    stop_grace_period: 500s
    stop_signal: SIGINT
    environment:
      - Proxy__UpstreamUrl__0=https://dotnet-nuget-prerelease.s3.eu-west-1.amazonaws.com
      - Proxy__UpstreamUrl__1=https://s3.eu-west-1.amazonaws.com/dotnet-nuget-prerelease
      - Proxy__UpstreamUrl__2=https://s3-eu-west-1.amazonaws.com/dotnet-nuget-prerelease
      - Proxy__PublicUrl=https://funfair-prerelease.nuget.local:5555
      - Proxy__Packages=/data
      - Proxy__JsonMaxAgeSeconds=600
    volumes:
      - cache_funfair_prerelease:/data
      - ./certs/funfair.nuget.local.pfx:/usr/src/app/server.pfx:r
    labels:
      - "autoheal=devpkg"
    networks:
      backend:

  devpkg-npm:
    image: verdaccio/verdaccio:latest
    container_name: devpkg-npm
    hostname: npm
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    environment:
      - VERDACCIO_PORT=4873
      - VERDACCIO_PUBLIC_URL=https://npm.local:5555
    volumes:
      - ./npm/conf:/verdaccio/conf
      - cache_npm_storage:/verdaccio/storage
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:4873/-/ping -O /dev/null || exit 1
      interval: 5s
      timeout: 4s
      retries: 5
      start_period: 120s
    labels:
      - "autoheal=devpkg"
    networks:
      backend:

  devpkg-nginx:
    image: docker-registry.markridgwell.com/credfeto/cache-nginx:latest
    container_name: devpkg-nginx
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    volumes:
      - ./certs:/etc/nginx/ssl:r
      - cache_nginx:/var/cache/nginx/proxy
    ports:
      - 5555:5555/tcp
      - 5555:5555/udp
      - 5554:5554/tcp
    depends_on:
      devpkg-proxy:
        condition: service_healthy
      devpkg-nuget:
        condition: service_healthy
      devpkg-funfair-prerelease:
        condition: service_healthy
      devpkg-funfair-release:
        condition: service_healthy
      devpkg-npm:
        condition: service_healthy
    networks:
      backend:
      frontend:
        aliases:
          - api.nuget.local
          - funfair.nuget.local
          - funfair-prerelease.nuget.local
          - npm.local
          - builds.dotnet.local

  devpkg-cache:
    image: docker-registry.markridgwell.com/credfeto/cache-checker:latest
    container_name: devpkg-cache
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    depends_on:
      devpkg-nginx:
        condition: service_healthy
    volumes:
      - ./certs:/local/certs:r
      - cache_downloads:/local/downloads
    labels:
      - "autoheal=devpkg"
    networks:
      frontend:

networks:
  backend:
    driver: bridge

  frontend:
    driver: bridge

volumes:
  cache_downloads:
    name: cache_downloads
    external: true
  cache_proxy:
    name: cache_proxy
    external: true
  cache_api_nuget_org:
    name: cache_api_nuget_org
    external: true
  cache_funfair_release:
    name: cache_funfair_release
    external: true
  cache_funfair_prerelease:
    name: cache_funfair_prerelease
    external: true
  cache_npm_conf:
    name: cache_npm_conf
    external: true
  cache_npm_storage:
    name: cache_npm_storage
    external: true
  cache_nginx:
    name: cache_nginx
    external: true

