#! /bin/sh

die() {
    echo
    echo "$@"
    exit 1
}

BASEDIR="$(dirname "$(readlink -f "$0")")"

add_ipv4_rule() {
    range="$1"
    port="$2"
    protocol="$3"

    sudo firewall-cmd --permanent --add-rich-rule="rule family=\"ipv4\" source address=\"${range}\" port protocol=\"${protocol}\" port=\"${port}\" accept"
}

add_private_ipv4_rules() {
    port="$1"
    protocol="$2"

    # RFC1918 private IPv4 ranges.
    for range in 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16; do
        add_ipv4_rule "$range" "$port" "$protocol"
    done
}

## devpkg-nuget
add_private_ipv4_rules 8081 tcp
add_private_ipv4_rules 8081 udp


## devpkg-funfair-release
add_private_ipv4_rules 8082 tcp
add_private_ipv4_rules 8082 udp

## devpkg-funfair-prerelease
add_private_ipv4_rules 8083 tcp
add_private_ipv4_rules 8083 udp

## devpkg-npm
add_private_ipv4_rules 8084 tcp
add_private_ipv4_rules 8084 udp

## devpkg-proxy
add_private_ipv4_rules 8085 tcp
add_private_ipv4_rules 8085 udp

## devpkg-nginx
add_private_ipv4_rules 5555 tcp
add_private_ipv4_rules 5555 udp
add_private_ipv4_rules 5554 tcp

## devpkg-dozzle
add_private_ipv4_rules 8080 tcp

sudo firewall-cmd --reload
