#! /bin/sh

die() {
    printf '\n\033[31m✗\033[0m %s\n' "$*" >&2
    exit 1
}

success() {
    printf '\n\033[32m✓\033[0m %s\n' "$*"
}

info() {
    printf '\n\033[32m→\033[0m %s\n' "$*"
}

BASEDIR="$(dirname "$(readlink -f "$0")")"
info "Script Dir: $BASEDIR"

info "Updating systemd scripts"
sed "s:/home/markr/work/credfeto-dev-package-cache:$BASEDIR:g" "systemd-unit/credfeto-package-cache.service" | sudo tee /etc/systemd/system/credfeto-package-cache.service || die "Could not install systemd service"
sudo cp "$BASEDIR/systemd-unit/credfeto-package-cache.timer" /etc/systemd/system/credfeto-package-cache.timer || die "Could not install systemd timer"

sed "s:/home/markr/work/credfeto-dev-package-cache:$BASEDIR:g" "systemd-unit/credfeto-package-cache-prune.service" | sudo tee /etc/systemd/system/credfeto-package-cache-prune.service || die "Could not install prune systemd service"
sudo cp "$BASEDIR/systemd-unit/credfeto-package-cache-prune.timer" /etc/systemd/system/credfeto-package-cache-prune.timer || die "Could not install prune systemd timer"

# shellcheck source=/dev/null
. /etc/os-release
if [ "$ID" = "arch" ]; then
  "$BASEDIR/trust-certs.arch"
elif [ "$ID" = "ubuntu" ]; then
  "$BASEDIR/trust-certs.ubuntu"
else
  info "Unsupported OS — you need to trust the local certs manually"
fi

info "systemd reload"
sudo systemctl daemon-reload || die "Could not reload systemd"

info "Enable credfeto-package-cache.timer"
sudo systemctl enable credfeto-package-cache.timer || die "Could not enable timer"

info "Start credfeto-package-cache.timer"
sudo systemctl start credfeto-package-cache.timer || die "Could not start timer"

info "Enable credfeto-package-cache-prune.timer"
sudo systemctl enable credfeto-package-cache-prune.timer || die "Could not enable prune timer"

info "Start credfeto-package-cache-prune.timer"
sudo systemctl start credfeto-package-cache-prune.timer || die "Could not start prune timer"

"$BASEDIR/update"

success "Done"
