#! /bin/sh

PROG=$0
die() {
    echo
    echo "$@"
    exit 1
}

BASEDIR="$(dirname "$(readlink -f "$0")")"

SOURCE="$BASEDIR/nuget.config"

[ -f "$SOURCE" ] || die "Could not find $SOURCE"

rm "$HOME/.nuget/NuGet/NuGet.Config"
ln -s "$SOURCE" "$HOME/.nuget/NuGet/NuGet.Config"
