#! /bin/bash

die() {
    printf '\n\033[31m✗\033[0m %s\n' "$*" >&2
    exit 1
}

success() {
    printf '\n\033[32m✓\033[0m %s\n' "$*"
}

info() {
    printf '\n\033[32m→\033[0m %s\n' "$*"
}

PACKAGE_ID=
PACKAGE_VERSION=
while [ $# -gt 0 ]; do
  key="$1"

  case $key in
    -P|--package-id)
      PACKAGE_ID="$2"
      shift # past argument
      shift # past value
      ;;
    -V|--version)
      PACKAGE_VERSION="$2"
      shift # past argument
      shift # past value
      ;;
    *)    # unknown option - skip here
      shift # past argument
      ;;
  esac
done

[ -z "$PACKAGE_ID" ] && die "Package Id not specified"
[ -z "$PACKAGE_VERSION" ] && die "Package Version not specified"

WORKFOLDER=/tmp/pkg
BASE=/cache/nuget/packages/nuget/packages
LOWER_PACKAGEID=${PACKAGE_ID,,}

PACKAGE_FOLDER=$BASE/$LOWER_PACKAGEID/$PACKAGE_VERSION
info "Folder: $PACKAGE_FOLDER"
[ -d "$PACKAGE_FOLDER" ] || sudo mkdir -p "$PACKAGE_FOLDER"

NUPKG_PACKAGE_FILENAME=$BASE/$LOWER_PACKAGEID/$PACKAGE_VERSION/$LOWER_PACKAGEID.$PACKAGE_VERSION.nupkg
NUSPEC_PACKAGE_FILENAME=$BASE/$LOWER_PACKAGEID/$PACKAGE_VERSION/$LOWER_PACKAGEID.nuspec

WORK_PACKAGE=$WORKFOLDER/$LOWER_PACKAGEID.zip
WORK_NUSPEC=$WORKFOLDER/$LOWER_PACKAGEID.nuspec
DOWNLOAD_URL=https://www.nuget.org/api/v2/package/$LOWER_PACKAGEID/$PACKAGE_VERSION

if [ ! -f "$NUPKG_PACKAGE_FILENAME" ] || [ ! -f "$NUSPEC_PACKAGE_FILENAME" ]; then
    [ -d "$WORKFOLDER" ] && rm -fr "$WORKFOLDER"
    mkdir -p "$WORKFOLDER"

    wget --no-verbose --tries=1 "$DOWNLOAD_URL" -O "$WORK_PACKAGE" || die "wget: Could not download"
    [ -f "$WORK_PACKAGE" ] || die "Downloaded file does not exist"
    unzip -v "$WORK_PACKAGE" "*.nuspec"
    unzip "$WORK_PACKAGE" "*.nuspec" -d "$WORKFOLDER/download"
    mv "$WORKFOLDER"/download/*.nuspec "$WORK_NUSPEC"

    sudo mv "$WORK_PACKAGE" "$NUPKG_PACKAGE_FILENAME" || die "Could not update $NUPKG_PACKAGE_FILENAME"
    sudo mv "$WORK_NUSPEC" "$NUSPEC_PACKAGE_FILENAME" || die "Could not update $NUSPEC_PACKAGE_FILENAME"

fi

[ -f "$NUPKG_PACKAGE_FILENAME" ] || die "$NUPKG_PACKAGE_FILENAME still does not exist after updating"
[ -f "$NUSPEC_PACKAGE_FILENAME" ] || die "$NUSPEC_PACKAGE_FILENAME still does not exist after updating"

success "Package $PACKAGE_ID $PACKAGE_VERSION downloaded"
