#! /bin/bash

die() {
    printf '\n\033[31m✗\033[0m %s\n' "$*" >&2
    exit 1
}

success() {
    printf '\n\033[32m✓\033[0m %s\n' "$*"
}

info() {
    printf '\n\033[32m→\033[0m %s\n' "$*"
}

BASEDIR="$(dirname "$(readlink -f "$0")")"

exec {lock_fd}>/tmp/devpkg || exit 1

/bin/flock -n "$lock_fd" || { printf '\n\033[31m✗\033[0m %s\n' "ERROR: flock() failed." >&2; exit 1; }

git pull

info "Stopping containers"
sudo docker compose stop && sudo docker compose rm --force

[ -d /cache ] || sudo mkdir /cache

info "Removing NGINX cache"
sudo rm -fr /cache/nginx

"$BASEDIR/update"

success "Done"
