#! /bin/bash

die() {
    printf '\n\033[31m✗\033[0m %s\n' "$*" >&2
    exit 1
}

success() {
    printf '\n\033[32m✓\033[0m %s\n' "$*"
}

info() {
    printf '\n\033[32m→\033[0m %s\n' "$*"
}

exec {lock_fd}>/tmp/devpkg || exit 1

/bin/flock -n "$lock_fd" || { printf '\n\033[31m✗\033[0m %s\n' "ERROR: flock() failed." >&2; exit 1; }

git pull

info "Stopping containers"
sudo docker compose stop && sudo docker compose rm --force

[ -d /cache ] || sudo mkdir /cache

info "Removing NGINX cache"
sudo rm -fr /cache/nginx

[ -d /cache/nginx ] || sudo mkdir /cache/nginx
[ -d /cache/npm ] || sudo mkdir /cache/npm
[ -d /cache/nuget ] || sudo mkdir /cache/nuget

sudo chown -R 10001:65533 /cache/npm || die "Could not set npm permissions"

sudo docker compose pull || die "Could not pull images"
sudo docker compose up --no-start || die "Could not build containers"

sudo docker compose up -d --remove-orphans || die "Could not start containers"
