#! /bin/bash

DOWNLOADS=$HOME/downloads
TMPBASE=${TMPDIR:-$HOME/tmp}
[ -d "$TMPBASE" ] || mkdir -p "$TMPBASE"
[ -d "$DOWNLOADS" ] || mkdir -p "$DOWNLOADS"

temporary_file_template="$TMPBASE/dotnet.XXXXXXXXX"
override_non_versioned_files=true
verbose=0

export DOTNET_SOURCE=https://builds.dotnet.microsoft.com
export PROXY_HOST=https://builds.dotnet.local:5555

USER_AGENT="DotnetVersionChecker/1.0.0"

die() {
    printf '\n\033[31m✗\033[0m %s\n' "$*" >&2
    exit 1
}

info() {
    printf '\n\033[32m→\033[0m %s\n' "$*"
}

say() {
    info "dotnet-install: $1"
}

say_verbose() {
    if [ "$verbose" = true ]; then
        info "$1"
    fi
}

say_err() {
    die "$1"
}

# args:
# zip_path - $1
# out_path - $2
extract_dotnet_package() {
    local zip_path="$1"
    local out_path="$2"
    local temp_out_path
    temp_out_path="$(mktemp -d "$temporary_file_template")"

    info "Extracting..."
    local failed=false
    tar -xvzf "$zip_path" -C "$temp_out_path" > /dev/null || failed=true

    if [ "$failed" = true ]; then
      doas rm -f "$zip_path" && say_verbose "Temporary archive file $zip_path was removed"
      say_err "Extraction failed"
    fi

    info "Install..."
    local folders_with_version_regex='^.*/[0-9]+\.[0-9]+[^/]+/'
    find "$temp_out_path" -type f | grep -Eo "$folders_with_version_regex" | sort | copy_files_or_dirs_from_list "$temp_out_path" "$out_path" false
    find "$temp_out_path" -type f | grep -Ev "$folders_with_version_regex" | copy_files_or_dirs_from_list "$temp_out_path" "$out_path" "$override_non_versioned_files"

    doas rm -rf "$temp_out_path"

    [ -f "$out_path/dotnet" ] || failed=true

    if [ "$failed" = true ]; then
        say_err "Extraction failed"
    fi
    return 0
}

# args:
# input_files - stdin
# root_path - $1
# out_path - $2
# override - $3
copy_files_or_dirs_from_list() {
    local root_path
    local out_path
    local override_switch
    root_path="$(remove_trailing_slash "$1")"
    out_path="$(remove_trailing_slash "$2")"
    local override="$3"
    override_switch="$(get_cp_options "$override")"

    cat | uniq | while read -r file_path; do
        local path
        local target
        path="$(remove_beginning_slash "${file_path#"$root_path"}")"
        target="$out_path/$path"
        if [ "$override" = true ] || ! { [ -d "$target" ] || [ -e "$target" ]; }; then
            doas mkdir -p "$out_path/$(dirname "$path")"
            if [ -d "$target" ]; then
                doas rm -rf "$target"
            fi
            doas cp -R "$override_switch" "$root_path/$path" "$target"
        fi
    done
}

# args:
# override - $1 (boolean, true or false)
get_cp_options() {
    local override="$1"
    local override_switch=""

    if [ "$override" = false ]; then
        override_switch="-n"

        # create temporary files to check if 'cp -u' is supported
        local tmp_dir
        tmp_dir="$(doas mktemp -d)"
        local tmp_file="$tmp_dir/testfile"
        local tmp_file2="$tmp_dir/testfile2"

        doas touch "$tmp_file"

        # use -u instead of -n if it's available
        if doas cp -u "$tmp_file" "$tmp_file2" 2>/dev/null; then
            override_switch="-u"
        fi

        # clean up
        doas rm -f "$tmp_file" "$tmp_file2"
        doas rm -rf "$tmp_dir"
    fi

    echo "$override_switch"
}

# args:
# input - $1
remove_trailing_slash() {
    local input="${1:-}"
    echo "${input%/}"
}

# args:
# input - $1
remove_beginning_slash() {
    local input="${1:-}"
    echo "${input#/}"
}

# args:
# version - $1
# sdk version - $2
install_dotnet_version() {
  local VERSION="$1"
  local SDK_VERSION="$2"

  info "**********************************************************************************************"
  info "* Installing dotnet: $VERSION"
  info "*       Current SDK: $SDK_VERSION"
  info "**********************************************************************************************"

  if [ -f "$DOTNET_ROOT/dotnet" ]; then
    local SDK_INSTALLED
    SDK_INSTALLED=$("$DOTNET_ROOT/dotnet" --list-sdks | cut -f 1 -d " " | grep -F "$SDK_VERSION")

    if [ "$SDK_INSTALLED" = "$SDK_VERSION" ]; then
      info "Already installed - skipping"
      return
    else
      info "New Install (Previous installed): $SDK_VERSION"
    fi
  else
    info "New Install (None installed): $SDK_VERSION"
  fi

  local TEMPORARY_FILE="$DOWNLOADS/$SDK_VERSION.tgz"

  if [ -f "$TEMPORARY_FILE" ]; then
    info "Already downloaded $TEMPORARY_FILE"
  else
    local DOWNLOAD_URL="$PROXY_HOST/dotnet/Sdk/$SDK_VERSION/dotnet-sdk-$SDK_VERSION-linux-musl-x64.tar.gz"
    info "Download $DOWNLOAD_URL to $TEMPORARY_FILE..."
    curl \
          --max-time 120 \
          --retry 5 \
          --retry-delay 0 \
          --retry-max-time 600 \
          -s \
          -L \
          -f \
          --user-agent "$USER_AGENT" \
          "$DOWNLOAD_URL" \
          -o "$TEMPORARY_FILE" || say_err "Could not download: $DOWNLOAD_URL"

    [ -f "$TEMPORARY_FILE" ] || say_err "Temp file not downloaded ($DOWNLOAD_URL)"
   fi

   extract_dotnet_package "$TEMPORARY_FILE" "$DOTNET_ROOT" || say_err "Could not install"

   "$DOTNET_ROOT/dotnet" --list-sdks || say_err "Dotnet $SDK_VERSION not installed properly"
}

get_latest_dotnet_sdk_version() {
    local DOTNET_CHANNEL_VERSION="$1"
    [ -z "$DOTNET_CHANNEL_VERSION" ] && die "Dotnet channel version not defined"
    curl \
       --max-time 120 \
       --retry 5 \
       --retry-delay 0 \
       --retry-max-time 600 \
       -s \
       -L \
       -f \
       --user-agent "$USER_AGENT" \
       https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json |
    jq --arg v "$DOTNET_CHANNEL_VERSION" -r '
            ."releases-index"
            | map(select(."channel-version" | contains($v)))
            | first(.[])
          | ."latest-sdk"'
}
