#! /bin/sh

# Check if nginx process is running
CHECK_TASK_PID=$(pidof nginx)
if [ -z "$CHECK_TASK_PID" ]; then
    exit 1
fi

# Check to see if nginx is responding
curl --fail http://localhost/health || exit 1

# Check to see if api nuget can be accessed
curl --fail --insecure https://api.nuget.local:5555/v3/index.json --resolve 'API.NUGET.LOCAL:5555:127.0.0.1' || exit 1

# Check to see if funfair nuget can be accessed
curl --fail --insecure https://funfair.nuget.local:5555/index.json --resolve 'FUNFAIR.NUGET.LOCAL:5555:127.0.0.1' || exit 1

# Check to see if funfair pre-release nuget can be accessed
curl --fail --insecure https://funfair-prerelease.nuget.local:5555/index.json --resolve 'FUNFAIR-PRERELEASE.NUGET.LOCAL:5555:127.0.0.1' || exit 1

# Check to see if npm nuget can be accessed
curl --fail --insecure https://npm.local:5555/-/ping --resolve 'NPM.LOCAL:5555:127.0.0.1' || exit 1

exit 0